### ISSUE TITLE
Dart 3 not supported

### ISSUE THREAD

**Issue by narayan954** [srplab/starcore_for_flutter#34]
Hi, I was trying to integrate python with flutter using this package but I found that it's not compatible with dart 3.
Is there a workaround (other than downgrading to dart2) to make this possible? All I can see is that people are getting a lot of [exceptions](https://stackoverflow.com/questions/73039739/i-am-trying-to-use-starflut-package-in-flutter-but-i-am-getting-a-lot-of-excepti)

It's important for me to integrate this somehow for my usecase. I have to develop an ios app in flutter and can't find solution.

**Comment by Umar888** [comment]
Is owner died?

**Comment by harunkurtdev** [comment]
@Umar888 
I think yes .... :(

**Comment by bogen85** [comment]
> Is owner died?

Well, last commit to this github account was back in May of 2021.
See https://github.com/srplab?tab=overview&from=2021-12-01&to=2021-12-31

**Comment by narayan954** [comment]
> > Is owner died?
> 
> Well, last commit to this github account was back in May of 2021. See https://github.com/srplab?tab=overview&from=2021-12-01&to=2021-12-31

Hoping others are incorrect, else RIP :'/
